# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sling < Formula
  desc "Data Integration made simple, from the command line. Extract and load data from popular data sources to destinations with high performance and ease."
  homepage "https:/slingdata.io/en/cli"
  version "0.87.35"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://ocral.nyc3.digitaloceanspaces.com/slingdata.io/dist/0.87.35/sling_0.87.35_Darwin_arm64.tar.gz"
      sha256 "29f2dff4fdfb077b9ca6772ce123edb07c4d98b6468868f8746e28024d3aac55"

      def install
        bin.install "sling"
      end
    end
    if Hardware::CPU.intel?
      url "https://ocral.nyc3.digitaloceanspaces.com/slingdata.io/dist/0.87.35/sling_0.87.35_Darwin_x86_64.tar.gz"
      sha256 "e712da30b394bdd560551f2a7552cc94e4878ef9e5e089b143e1a7d2e74a8541"

      def install
        bin.install "sling"
      end
    end
  end
end
